services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --overprovisioned
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  ingest-kraken:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    container_name: ingest-kraken
    command: ["python", "ingest_kraken.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
    depends_on:
      - redpanda
    restart: unless-stopped

  ingest-alpaca:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    container_name: ingest-alpaca
    command: ["python", "ingest_alpaca.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
    env_file:
      - .env
    depends_on:
      - redpanda
    restart: unless-stopped

  processor:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    container_name: processor
    command: ["python", "processor.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
      - REDIS_HOST=rt-dashboard-redis.wqyj6u.0001.use2.cache.amazonaws.com
      - REDIS_PORT=6379
    depends_on:
      - redpanda
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=rt-dashboard-redis.wqyj6u.0001.use2.cache.amazonaws.com
      - REDIS_PORT=6379
    depends_on:
      - redpanda
    restart: unless-stopped
